# Generated by Django 3.1.3 on 2020-12-03 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20201202_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='h',
            field=models.IntegerField(default=300),
        ),
        migrations.AddField(
            model_name='image',
            name='w',
            field=models.IntegerField(default=300),
        ),
    ]
